In [53]:
print("Hello World!")

Hello World!

In [54]:
excel_file_path = 'C:\\Desktop\\Renewable Energy Adoption\\IRENA_Stats_extract_2024 H2(1).xlsx'  # Ensure the path points to the actual file
import pandas as pd

# Load the actual Excel file (not the temporary one)
excel_data = pd.ExcelFile(excel_file_path)

# List all the sheet names
print(excel_data.sheet_names)

# Load each sheet into a separate DataFrame
# sheet1 = excel_data.parse(sheet_name='Sheet1')  # Replace 'Sheet1' with the actual sheet name
# sheet2 = excel_data.parse(sheet_name='Sheet2')

['About', 'Renewable Growth', 'Sheet4', 'Country', 'Region', 'Global', 'Sheet2', 'Sheet1', 'All data']

In [55]:
Country = excel_data.parse(sheet_name='Country')

In [56]:
Country

,Region,Sub-region,Country,ISO3 code,M49 code,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Heat Generation (TJ),Public Flows (2021 USD M),SDG 7a1 Intl. Public Flows (2021 USD M),SDG 7b1 RE capacity per capita (W/inhabitant)
0,Africa,Northern Africa,Algeria,DZA,12,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2014,NaN,NaN,NaN,0.573521,NaN,NaN
1,Africa,Northern Africa,Algeria,DZA,12,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2017,NaN,NaN,NaN,0.296828,NaN,NaN
2,Africa,Northern Africa,Algeria,DZA,12,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2000,24585.0,5459.01,NaN,NaN,NaN,NaN
3,Africa,Northern Africa,Algeria,DZA,12,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2001,25781.0,5455.50,NaN,NaN,NaN,NaN
4,Africa,Northern Africa,Algeria,DZA,12,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2002,26994.0,5891.01,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90547,Unspecified countries,(blank),Unspecified countries,XDX,99049,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2014,NaN,NaN,NaN,0.038592,NaN,NaN
90548,Unspecified countries,(blank),Unspecified countries,XDX,99049,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2016,NaN,NaN,NaN,1.381940,NaN,NaN
90549,Unspecified countries,(blank),Unspecified countries,XDX,99049,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2019,NaN,NaN,NaN,11.495979,NaN,NaN
90550,Unspecified countries,(blank),Unspecified countries,XDX,99049,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2020,NaN,NaN,NaN,3.824680,NaN,NaN
90551,Unspecified countries,(blank),Unspecified countries,XDX,99049,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2022,NaN,NaN,NaN,0.134870,NaN,NaN

### Wrangling

In [57]:

# List of columns to drop
columns_to_drop = [
    'Sub-region', 
    'ISO3 code', 
    'M49 code', 
    'Heat Generation (TJ)', 
    'SDG 7a1 Intl. Public Flows (2021 USD M)', 
    'SDG 7b1 RE capacity per capita (W/inhabitant)'
]

# Drop the specified columns
Country_sheet = Country.drop(columns=columns_to_drop)

# Optional: Save the modified DataFrame back to a CSV or another format
# df.to_csv('your_modified_data.csv', index=False)

# Display the updated DataFrame
Country_sheet.head()

,Region,Country,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Public Flows (2021 USD M)
0,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2014,NaN,NaN,0.573521
1,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2017,NaN,NaN,0.296828
2,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2000,24585.0,5459.01,NaN
3,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2001,25781.0,5455.50,NaN
4,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2002,26994.0,5891.01,NaN

In [58]:
Country_sheet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90552 entries, 0 to 90551
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Region                               90552 non-null  object
 1   Country                              90552 non-null  object
 2   RE or Non-RE                         90552 non-null  object
 3   Group Technology                     90552 non-null  object
 4   Technology                           90552 non-null  object
 5   Sub-Technology                       90552 non-null  object
 6   Producer Type                        90552 non-null  object
 7   Year                                 90552 non-null  int64
 8   Electricity Generation (GWh)         35198 non-null  float64
 9   Electricity Installed Capacity (MW)  36359 non-null  float64
 10  Public Flows (2021 USD M)            7840 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 7.6+ MB

In [64]:


# Define the values you want to filter out from 'Group Technology'
values_to_drop = ["Multiple renewables*", "Other renewable energy"]

# Drop rows where 'Group Technology' matches any of the values in the list
Country_sheet_11 = Country_sheet[~Country_sheet['Group Technology'].isin(values_to_drop)]

# Optional: Save the modified DataFrame back to a CSV or another format
# Country_sheet.to_csv('your_modified_data.csv', index=False)

# Display the updated DataFrame
Country_sheet_11.head()

,Region,Country,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Public Flows (2021 USD M)
0,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2014,NaN,NaN,0.573521
1,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2017,NaN,NaN,0.296828
2,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2000,24585.0,5459.01,NaN
3,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2001,25781.0,5455.50,NaN
4,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2002,26994.0,5891.01,NaN

In [65]:
Country_sheet_11.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88361 entries, 0 to 90551
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Region                               88361 non-null  object
 1   Country                              88361 non-null  object
 2   RE or Non-RE                         88361 non-null  object
 3   Group Technology                     88361 non-null  object
 4   Technology                           88361 non-null  object
 5   Sub-Technology                       88361 non-null  object
 6   Producer Type                        88361 non-null  object
 7   Year                                 88361 non-null  int64
 8   Electricity Generation (GWh)         35198 non-null  float64
 9   Electricity Installed Capacity (MW)  36359 non-null  float64
 10  Public Flows (2021 USD M)            5808 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 8.1+ MB

In [66]:


# Define the values you want to filter out from 'Group Technology'
values_to_drop = ["Unspecified countries", "Multilateral"]

# Drop rows where 'Group Technology' matches any of the values in the list
Country_sheet_11_11 = Country_sheet_11[~Country_sheet_11['Region'].isin(values_to_drop)]

# Optional: Save the modified DataFrame back to a CSV or another format
# Country_sheet_11.to_csv('your_modified_data.csv', index=False)

# Display the updated DataFrame
Country_sheet_11_11.head()

,Region,Country,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Public Flows (2021 USD M)
0,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2014,NaN,NaN,0.573521
1,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2017,NaN,NaN,0.296828
2,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2000,24585.0,5459.01,NaN
3,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2001,25781.0,5455.50,NaN
4,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2002,26994.0,5891.01,NaN

In [67]:
Country_sheet_11_11.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88234 entries, 0 to 90405
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Region                               88234 non-null  object
 1   Country                              88234 non-null  object
 2   RE or Non-RE                         88234 non-null  object
 3   Group Technology                     88234 non-null  object
 4   Technology                           88234 non-null  object
 5   Sub-Technology                       88234 non-null  object
 6   Producer Type                        88234 non-null  object
 7   Year                                 88234 non-null  int64
 8   Electricity Generation (GWh)         35198 non-null  float64
 9   Electricity Installed Capacity (MW)  36359 non-null  float64
 10  Public Flows (2021 USD M)            5681 non-null   float64
dtypes: float64(3), int64(1), object(7)
memory usage: 8.1+ MB

In [68]:
# Check unique values in 'Group Technology' to confirm the exact values
unique_values = Country_sheet_11_11['Region'].unique()
unique_values

array(['Africa', 'Americas', 'Asia', 'Europe', 'Oceania'], dtype=object)

In [81]:
unique_values = Country_sheet_11_11['Group Technology'].unique()
unique_values

array(['Fossil fuels', 'Nuclear', 'Bioenergy', 'Geothermal energy',
       'Hydropower (excl. Pumped Storage)', 'Marine energy',
       'Solar energy', 'Wind energy', 'Pumped storage',
       'Other non-renewable energy'], dtype=object)

In [69]:
unique_values = Country_sheet_11_11['Technology'].unique()
unique_values

array(['Natural gas', 'Oil', 'Nuclear', 'Solid biofuels',
       'Geothermal energy', 'Renewable hydropower', 'Marine energy',
       'Solar energy', 'Solar photovoltaic', 'Solar thermal energy',
       'Onshore wind energy', 'Coal and peat', 'Fossil fuels n.e.s.',
       'Biogas', 'Pumped storage', 'Non-renewable municipal waste',
       'Liquid biofuels', 'Renewable municipal waste',
       'Other non-renewable energy', 'Mixed Hydro Plants',
       'Offshore wind energy'], dtype=object)

In [70]:
unique_values = Country_sheet_11_11['Sub-Technology'].unique()
unique_values

array(['Natural gas', 'Oil', 'Nuclear',
       'Other primary solid biofuels n.e.s.', 'Geothermal energy',
       'Renewable hydropower', 'Marine energy', 'Solar energy',
       'Off-grid Solar photovoltaic', 'On-grid Solar photovoltaic',
       'Solar mini-grids', 'Concentrated solar power',
       'Onshore wind energy', 'Coal and peat', 'Fossil fuels n.e.s.',
       'Sewage sludge gas', 'Bagasse', 'SHS (>50W)', 'Pumped storage',
       'Landfill gas', 'Solar thermal energy', 'Solar lights (<11W)',
       'SHS (11-50W)', 'Biogas n.e.s.', 'Non-renewable municipal waste',
       'Biogas', 'Other biogases from anaerobic fermentation',
       'Other liquid biofuels', 'Wood waste',
       'Other vegetal and agricultural waste',
       'Renewable municipal waste', 'Rice husks',
       'Conventional biodiesel', 'Straw', 'Wood fuel', 'Liquid biofuels',
       'Biomass pellets and briquettes',
       'Biogases from thermal processes', 'Other non-renewable energy',
       'Advanced biodiesel', 'Biodiesel', 'Biogasoline', 'Black liquor',
       'Energy crops', 'Mixed Hydro Plants', 'Animal waste',
       'Advanced biogasoline', 'Renewable industrial waste',
       'Offshore wind energy', 'Other solar thermal energy'], dtype=object)

#### Converting GWh to MWh

In [71]:
Country_sheet_11_11['Electricity Generation (MWh)'] = Country_sheet_11_11['Electricity Generation (GWh)'] * 1000

C:\Users\godwi\AppData\Local\Temp\ipykernel_27540\4235293601.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Country_sheet_11_11['Electricity Generation (MWh)'] = Country_sheet_11_11['Electricity Generation (GWh)'] * 1000

In [73]:
## Define Emission Factors

emission_factors = {
    'Natural gas': 490,
    'Oil': 740,
    'Coal and peat': 935,  # Average of 820-1050
    'Fossil fuels n.e.s.': 800,
    'Other primary solid biofuels n.e.s.': 275,  # Average of 100-450
    'Non-renewable municipal waste': 750,  # Average of 500-1000
    'Nuclear': 0,
    'Other non-renewable energy': 850  # Average of 700-1000
}

In [74]:
## Calculate Carbon Emissions

Country_sheet_11_11['Carbon Emission (kg CO₂)'] = Country_sheet_11_11.apply(
    lambda row: (
        row['Electricity Generation (MWh)'] * emission_factors.get(row['Sub-Technology'], 0)
        if row['Electricity Generation (GWh)'] > 0 else 0
    ),
    axis=1
)

C:\Users\godwi\AppData\Local\Temp\ipykernel_27540\1073889907.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Country_sheet_11_11['Carbon Emission (kg CO₂)'] = Country_sheet_11_11.apply(

In [75]:
Country_sheet_11_11

,Region,Country,RE or Non-RE,Group Technology,Technology,Sub-Technology,Producer Type,Year,Electricity Generation (GWh),Electricity Installed Capacity (MW),Public Flows (2021 USD M),Electricity Generation (MWh),Carbon Emission (kg CO₂)
0,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2014,NaN,NaN,0.573521,NaN,0.000000e+00
1,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,All types,2017,NaN,NaN,0.296828,NaN,0.000000e+00
2,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2000,24585.0,5459.01,NaN,24585000.0,1.204665e+10
3,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2001,25781.0,5455.50,NaN,25781000.0,1.263269e+10
4,Africa,Algeria,Total Non-Renewable,Fossil fuels,Natural gas,Natural gas,On-grid electricity,2002,26994.0,5891.01,NaN,26994000.0,1.322706e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90401,Oceania,Tuvalu,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2018,NaN,NaN,NaN,NaN,0.000000e+00
90402,Oceania,Tuvalu,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2019,NaN,NaN,NaN,NaN,0.000000e+00
90403,Oceania,Tuvalu,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2020,NaN,NaN,NaN,NaN,0.000000e+00
90404,Oceania,Tuvalu,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2021,NaN,NaN,NaN,NaN,0.000000e+00
90405,Oceania,Tuvalu,Total Renewable,Wind energy,Onshore wind energy,Onshore wind energy,All types,2022,NaN,NaN,NaN,NaN,0.000000e+00

In [76]:
Country_sheet_11_11.info()

<class 'pandas.core.frame.DataFrame'>
Index: 88234 entries, 0 to 90405
Data columns (total 13 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Region                               88234 non-null  object
 1   Country                              88234 non-null  object
 2   RE or Non-RE                         88234 non-null  object
 3   Group Technology                     88234 non-null  object
 4   Technology                           88234 non-null  object
 5   Sub-Technology                       88234 non-null  object
 6   Producer Type                        88234 non-null  object
 7   Year                                 88234 non-null  int64
 8   Electricity Generation (GWh)         35198 non-null  float64
 9   Electricity Installed Capacity (MW)  36359 non-null  float64
 10  Public Flows (2021 USD M)            5681 non-null   float64
 11  Electricity Generation (MWh)         35198 non-null  float64
 12  Carbon Emission (kg CO₂)             88234 non-null  float64
dtypes: float64(5), int64(1), object(7)
memory usage: 9.4+ MB

In [78]:
Country_sheet_11_11['Country'] = Country_sheet_11_11['Country'].replace('United States of America (the)', 'USA')

C:\Users\godwi\AppData\Local\Temp\ipykernel_27540\828909390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Country_sheet_11_11['Country'] = Country_sheet_11_11['Country'].replace('United States of America (the)', 'USA')

In [80]:
# Export the DataFrame to a CSV file
Country_sheet_11_11.to_csv('Renewable Energy data.csv', index=False)